[package]
name = "lilac"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
memfd = "0.6.5"
mmap = "0.1.1"
wayland-client = "0.31.11"
wayland-protocols = { version = "0.32.9", features = ["client", "staging"] }
